# Generated by Django 5.1.6 on 2025-05-02 11:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('netbox_firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bios',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='netbox_firmware_bios_unique_name', violation_error_message='Device name must be unique.'),
        ),
    ]
