# Generated by Django 5.1.6 on 2025-05-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('netbox_firmware', '0002_bios_netbox_firmware_bios_unique_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='biosassignment',
            constraint=models.UniqueConstraint(fields=('device',), name='unique_bios_per_device'),
        ),
        migrations.AddConstraint(
            model_name='biosassignment',
            constraint=models.UniqueConstraint(fields=('module',), name='unique_bios_per_module'),
        ),
        migrations.AddConstraint(
            model_name='firmwareassignment',
            constraint=models.UniqueConstraint(fields=('device',), name='unique_firmware_per_device'),
        ),
        migrations.AddConstraint(
            model_name='firmwareassignment',
            constraint=models.UniqueConstraint(fields=('module',), name='unique_firmware_per_module'),
        ),
    ]
