# Generated by Django 5.1.6 on 2025-03-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmware',
            old_name='comment',
            new_name='comments',
        ),
    ]
