# Generated by Django 5.1.6 on 2025-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('firmware_management', '0001_initial'),
        ('netbox_inventory', '0009_add_rack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmwareassignment',
            options={'ordering': ('firmware', 'device', 'module', 'inventory_item')},
        ),
        migrations.AddField(
            model_name='firmware',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='firmware-files'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='firmwareassignment',
            constraint=models.CheckConstraint(condition=models.Q(('device__isnull', False), ('module__isnull', False), ('inventory_item__isnull', False), _connector='OR'), name='either_device_or_module_or_inventory_item_required'),
        ),
    ]
