# Generated by Django 5.1.6 on 2025-03-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('firmware_management', '0002_firmware_device_type_firmware_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareassignment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FirmwareAssignment', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='firmwareassignment',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FirmwareAssignment', to='dcim.devicetype'),
        ),
        migrations.AddField(
            model_name='firmwareassignment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FirmwareAssignment', to='dcim.manufacturer'),
        ),
    ]
