# Generated by Django 5.1.6 on 2025-03-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('firmware_management', '0002_firmwareassignment_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareassignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FirmwareAssignment', to='dcim.module'),
        ),
    ]
