# Generated by Django 5.1.6 on 2025-03-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('firmware_management', '0003_firmwareassignment_either_device_type_or_module_type_or_inventory_item_type_required'),
        ('netbox_inventory', '0009_add_rack'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='firmware',
            name='either_manufacturer_or_device_type_or_inventory_item_type_or_module_type_required',
        ),
        migrations.AddConstraint(
            model_name='firmware',
            constraint=models.CheckConstraint(condition=models.Q(('device_type__isnull', False), ('module_type__isnull', False), ('inventory_item_type__isnull', False), _connector='OR'), name='either_device_type_or_inventory_item_type_or_module_type_required'),
        ),
    ]
