# Generated by Django 5.1.6 on 2025-03-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_management', '0004_firmwareassignment_firmware_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmware',
            name='description',
        ),
    ]
