# Generated by Django 5.1.6 on 2025-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('firmware_management', '0005_bios_biosassignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bios',
            options={'ordering': ('name', 'device_type', 'module_type')},
        ),
        migrations.AlterModelOptions(
            name='firmware',
            options={'ordering': ('name', 'device_type', 'module_type', 'manufacturer')},
        ),
        migrations.RemoveConstraint(
            model_name='bios',
            name='bios_device_type_or_inventory_item_type_or_module_type_required',
        ),
        migrations.RemoveConstraint(
            model_name='firmwareassignment',
            name='either_device_or_module_or_inventory_item_required',
        ),
        migrations.RemoveConstraint(
            model_name='firmwareassignment',
            name='either_device_type_or_module_type_or_inventory_item_type_required',
        ),
        migrations.AlterUniqueTogether(
            name='bios',
            unique_together={('name', 'device_type', 'module_type')},
        ),
        migrations.AlterUniqueTogether(
            name='firmware',
            unique_together={('name', 'manufacturer', 'device_type', 'module_type')},
        ),
        migrations.RemoveField(
            model_name='firmwareassignment',
            name='inventory_item_type',
        ),
        migrations.AddConstraint(
            model_name='bios',
            constraint=models.CheckConstraint(condition=models.Q(('device_type__isnull', False), ('module_type__isnull', False), _connector='OR'), name='bios_device_type_or_module_type_required'),
        ),
        migrations.AddConstraint(
            model_name='firmware',
            constraint=models.CheckConstraint(condition=models.Q(('device_type__isnull', False), ('module_type__isnull', False), _connector='OR'), name='firmware_either_device_type_or_module_type_required'),
        ),
        migrations.AddConstraint(
            model_name='firmwareassignment',
            constraint=models.CheckConstraint(condition=models.Q(('device__isnull', False), ('module__isnull', False), ('inventory_item__isnull', False), _connector='OR'), name='firmassign_either_device_or_module_or_inventory_item_required'),
        ),
        migrations.AddConstraint(
            model_name='firmwareassignment',
            constraint=models.CheckConstraint(condition=models.Q(('device_type__isnull', False), ('module_type__isnull', False), _connector='OR'), name='firmassign_either_device_type_or_module_type_required'),
        ),
        migrations.RemoveField(
            model_name='bios',
            name='inventory_item_type',
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='inventory_item_type',
        ),
    ]
