# Generated by Django 5.1.6 on 2025-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('firmware_management', '0006_alter_bios_options_alter_firmware_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biosassignment',
            options={'ordering': ('bios', 'device', 'module')},
        ),
        migrations.AlterModelOptions(
            name='firmwareassignment',
            options={'ordering': ('firmware', 'device', 'module')},
        ),
        migrations.RemoveConstraint(
            model_name='biosassignment',
            name='bios_device_or_module_or_inventory_item_required',
        ),
        migrations.RemoveField(
            model_name='biosassignment',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='firmwareassignment',
            name='inventory_item',
        ),
        migrations.AddConstraint(
            model_name='biosassignment',
            constraint=models.CheckConstraint(condition=models.Q(('device__isnull', False), ('module__isnull', False), _connector='OR'), name='bios_device_or_module_required'),
        ),
        migrations.AddConstraint(
            model_name='firmwareassignment',
            constraint=models.CheckConstraint(condition=models.Q(('device__isnull', False), ('module__isnull', False), _connector='OR'), name='firmassign_either_device_or_module_required'),
        ),
    ]
