# Generated by Django 5.1.6 on 2025-04-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_management', '0007_alter_biosassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='firmware',
            name='either_device_type_or_inventory_item_type_or_module_type_required',
        ),
    ]
